import { readdir, readFile, writeFile } from "node:fs/promises";
import assert from "node:assert/strict";

// Vendored Simple Icons only. Keep inherited paint on a group because the
// generated entry intentionally exports just viewBox and inner markup.
function extract(svg) {
  const clean = svg.replace(/<\?xml[\s\S]*?\?>/g, "").replace(/<!--[\s\S]*?-->/g, "").trim();
  const root = clean.match(/^<svg\b([^>]*)>([\s\S]*)<\/svg>$/);
  assert(root, "Expected one SVG root");
  const attributes = Object.fromEntries([...root[1].matchAll(/([\w:-]+)\s*=\s*(["'])(.*?)\2/g)].map((m) => [m[1], m[3]]));
  assert(attributes.viewBox, "SVG must have a viewBox");
  const paint = Object.entries(attributes)
    .filter(([key]) => /^(fill|fill-rule|stroke|stroke-width|stroke-linecap|stroke-linejoin|opacity|style|color)$/.test(key))
    .map(([key, value]) => `${key}="${value.replaceAll('"', "&quot;")}"`).join(" ");
  const inner = root[2].replace(/<title\b[^>]*>[\s\S]*?<\/title>/g, "").replace(/\s+/g, " ").replace(/>\s+</g, "><").trim();
  assert(inner, "SVG must contain artwork");
  return { viewBox: attributes.viewBox, path: paint ? `<g ${paint}>${inner}</g>` : inner };
}

assert.deepEqual(extract('<?xml version="1.0"?><!-- icon --><svg viewBox="0 0 24 24" fill="#123456">\n<title>Icon</title><path d="M0 0"/>\n</svg>'), {
  viewBox: "0 0 24 24", path: '<g fill="#123456"><path d="M0 0"/></g>',
});

const directory = new URL("../public/icons/", import.meta.url);
const files = (await readdir(directory)).filter((file) => file.endsWith(".svg")).sort();
const icons = Object.fromEntries(await Promise.all(files.map(async (file) => [file.slice(0, -4), extract(await readFile(new URL(file, directory), "utf8"))])));
const output = '// lib/icon-data.ts  (GENERATED by scripts/build-icons.mjs, do not edit by hand)\nexport type IconEntry = { viewBox: string; path: string };\nexport const ICONS: Record<string, IconEntry> = ' + JSON.stringify(icons, null, 2) + ';\n';
await writeFile(new URL("../lib/icon-data.ts", import.meta.url), output);
console.log(`Generated ${files.length} icons (${Buffer.byteLength(output)} bytes).`);
